---
- name: Webserver setup
  hosts: webservers
  become: true
  vars:
    packagename: apache2

  tasks:
    - debug: 
        msg: "This is {{packagename}} installation"
   
    - name: Install apache
      apt:
        name: "{{packagename}}"
        state: present

    - name: Start service
      service: 
        name: "{{packagename}}"
        state: started


- name: Database server setup
  hosts: dbservers
  become: true
  vars:
    dbname: mysql-server

  tasks:
    - debug: 
        var: dbname

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: "{{dbname}}"
        state: present
      register: dbout

    - name: print db output
      debug: 
        var: dbout

    # Additional tasks for database configuration and setup can be added here
 
      
